version: '3'

services:
  postgres:
    restart: always
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'babysitter'
      POSTGRES_PASSWORD: 'babysitterpass'
      POSTGRES_DB: 'babysitter'
    expose:
      - "5432"
  web:
    restart: always
    build: .
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - postgres
    volumes:
      - static:/code/static
      - ./:/code
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/usr/share/nginx/html/static:ro
    ports:
      - "80:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
volumes: 
  data:
  static: