version: '3'

services:
  postgres:
    restart: always
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'babysitter'
      POSTGRES_PASSWORD: 'babysitterpass'
      POSTGRES_DB: 'babysitter'
    ports:
      - 5432:5432
  web:
    restart: always
    build: .
    ports:
      - "8081:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/code
  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      - postgres
volumes: 
  data:
