# Generated by Django 4.2 on 2023-04-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.IntegerField(default=12)),
                ('years_of_experience', models.IntegerField(default=1)),
                ('bio', models.CharField(default='', max_length=900)),
                ('published', models.BooleanField(default=False)),
                ('full_name', models.CharField(default='', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='babysitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=250)),
                ('payment_method', models.IntegerField(choices=[(1, 'Card'), (2, 'Cash')], default=2)),
                ('number_of_children', models.IntegerField(default=1)),
                ('special_needs', models.CharField(default='', max_length=500)),
                ('published', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('notes', models.CharField(max_length=500)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtable', to='app.babysitter')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtable', to='app.family')),
            ],
        ),
    ]
