# Generated by Django 4.2 on 2023-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bookingtable_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
