# Generated by Django 4.2 on 2023-05-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_babysitter_for_grandparents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='published',
        ),
    ]
