# Generated by Django 4.2 on 2023-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_babysitter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='avatar',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='birthday',
            field=models.DateField(auto_now_add=True),
        ),
    ]
