# Generated by Django 4.2 on 2023-05-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_babysitter_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='age',
        ),
    ]
