# Generated by Django 4.2 on 2023-05-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_babysitter_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.ImageField(upload_to='certificates')),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.babysitter')),
            ],
        ),
    ]
