# Generated by Django 4.2 on 2023-06-01 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def save_foo_as_bar(apps, schema_editor):
    old_model = apps.get_model("app", "Address")

    old_model.objects.create(name="Умолочание")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_rate_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.RunPython(save_foo_as_bar),
        migrations.AlterField(
            model_name='babysitter',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='address_type',
            field=models.ManyToManyField(to='app.address'),
        ),
        migrations.AddField(
            model_name='family',
            name='address_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.address'),
        ),
    ]
