# Generated by Django 4.2 on 2023-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_address_alter_babysitter_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='for_grandparents',
        ),
        migrations.AddField(
            model_name='babysitter',
            name='baby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='detsad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='threeToFive',
            field=models.BooleanField(default=False),
        ),
    ]
