# Generated by Django 4.2 on 2023-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_babysitter_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='hourly_rate',
            field=models.IntegerField(default=500),
        ),
    ]
