# Generated by Django 4.2 on 2023-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.IntegerField(default=12)),
                ('years_of_experience', models.IntegerField(default=1)),
                ('bio', models.CharField(default='', max_length=900)),
                ('avability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=0, max_length=250)),
                ('payment_method', models.IntegerField(choices=[(1, 'Card'), (2, 'Cash')], default=2)),
                ('number_of_children', models.IntegerField(default=1)),
                ('special_needs', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
