# Generated by Django 4.2 on 2023-04-10 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Family', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='babysitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtable', to='app.babysitter'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtable', to='app.family'),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='babysitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
