# Generated by Django 4.2 on 2023-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_babysitter_user_alter_family_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='has_been_redacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='family',
            name='has_been_redacted',
            field=models.BooleanField(default=False),
        ),
    ]
