# Generated by Django 4.2 on 2023-05-08 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_family_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 5, 8, 10, 47, 50, 690785, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
