# Generated by Django 4.2 on 2023-04-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_babysitter_has_been_redacted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babysitter',
            old_name='has_been_redacted',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='has_been_redacted',
            new_name='published',
        ),
    ]
