# Generated by Django 4.2 on 2023-04-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_has_been_redacted_babysitter_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='avability',
        ),
    ]
