# Generated by Django 4.2 on 2023-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_babysitter_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
