# Generated by Django 4.2 on 2023-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_babysitter_avability'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='full_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
