# Generated by Django 4.2 on 2023-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_babysitter_education_alter_babysitter_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
