name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build
    - name: Login to registry
      run: docker login -p ${{ secrets.REGISTRY_SECRET }} -u ${{ secrets.REGISTRY_SECRET }} registry.digitalocean.com
    - name: Upload to registry
      run: docker compose -f docker-compose.yml -f docker-compose.prod.yml push

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: kompose convert -f docker-compose.yaml |
                kubectl apply -f . |
                kubectl get po

